### ISSUE TITLE
Bar tests relying on visiting webpages outside the deployment/host

### ISSUE THREAD

**Issue by zachblume** [zachblume/autospec#10]

**Comment by craigmulligan** [comment]
Happy to pick this up. Did you have an example of it happening? Also did you have an idea of how you'd tackle it? I think a test like: "github link should navigate to github.com" can be useful and so we should still allow for navigating to an external host but we should also ensure we stop after navigating to the external host.

**Comment by zachblume** [comment]
On some previous tests where the model was clicking a little more aimlessly, it clicked on the "Part of [TodoMVC](http://todomvc.com/)" link and then hallucinated an API action for clicking the back button. I'm not sure how to handle -- this feels like a playwright nav issue, we don't want to stub out requests to other hosts but just make page navigation fail with say a custom error code like 499 that we also explain to the model (`if you encounter 499 it's because you accidently strayed onto another website, so use goto navigation API to correctly your browsing` or something). Maybe placing a listener on page event and bubbling an error to the playwright step, so it gets fed back to the message history through the existing error recovery?
```
page.on('framenavigating', (url) => {
    const targetUrl = new URL(url);
    if (targetUrl.host !== allowedHost) {
      console.log(`Navigation to external host blocked: ${targetUrl.href}`);
      // Throw a custom error or handle as needed
      throw new Error('499 Navigation to external host blocked');
    }
  });
```

**Comment by craigmulligan** [comment]
Sounds good. I wonder if even just mentioning it in the initial system prompt would work. Eg if the current urls host != allowed host then use the goto url to navigate back to allowedUrl. Either way we should setup a proper test case for it so we can ensure whatever solution we use works. Will put this on the back-burner for now.
